### ISSUE TITLE
populating the database with mock data

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#10]
for prototyping purposes I will fill the database with some data

**Comment by rsgc-dunphy-j** [comment]
This will be done through a login page

**Comment by rsgc-edwards-g** [comment]
you'll have to wait for the register page

**Comment by rsgc-edwards-g** [comment]
Just an fyi @rsgc-dunphy-j and @rsgc-power-r, I recently had to recreate the database so there is no mock data in there other than for my test user, whose username is dew and password is the.

**Comment by rsgc-power-r** [comment]
Is this still an issue? Just curious...

**Comment by rgordonathome** [comment]
If you create some data (through pages you've written) that you want to keep as mock data after future DB resets (if needed) there is a command called "mysqldump" that will allow this. Ask me in class, it's straightforward and pretty useful.

**Comment by rgordonathome** [comment]
This issue needs a label, milestone, and assignee.

**Comment by rsgc-edwards-g** [comment]
With the register pages, we can add data to certain database tables when we want. We also have access to the database through SQL in the Terminal window. Due to occasional changes to the database initialization script, we do lose data from time to time. However, this is easily resolved. Currently, I still need to get the data dump from Ms. Wagar, which will further populate the database.
